# Generated by Django 4.1 on 2022-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Detailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_No', models.CharField(max_length=16)),
                ('Experience', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=300)),
                ('Resume', models.FileField(upload_to='')),
                ('submitted_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
