# Generated by Django 4.1 on 2022-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=300)),
                ('Resume', models.FileField(upload_to='')),
                ('Submitted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate_Detailes',
        ),
    ]
