# Generated by Django 4.1 on 2022-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0003_careers_table_delete_candidate_detailes'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers_table',
            name='JobOrderID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
