# Generated by Django 4.1 on 2022-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0004_careers_table_joborderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
