# Generated by Django 4.1 on 2022-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0005_alter_careers_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
