# Generated by Django 4.1 on 2022-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0006_alter_careers_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careers_table',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
