# Generated by Django 4.1 on 2022-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0007_alter_careers_table_email_alter_careers_table_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='userinfo',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
