# Generated by Django 4.1 on 2022-10-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0008_contactus_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='userinfo',
        ),
    ]
