# Generated by Django 4.1 on 2023-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0009_remove_contactus_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('submitted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebook_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumber', models.IntegerField(null=True, unique=True)),
                ('ebook_pdf', models.FileField(upload_to='static/assets/E-Books/')),
                ('ebook_image', models.FileField(upload_to='static/assets/E-Books/images/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Whitepaper_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('submitted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitepaper_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wnumber', models.IntegerField(null=True, unique=True)),
                ('whitepaper_pdf', models.FileField(upload_to='static/assets/Whitepapers/')),
                ('whitepaper_image', models.FileField(upload_to='static/assets/Whitepapers/images/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
