# Generated by Django 4.1 on 2023-01-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0010_ebook_download_ebook_pdf_whitepaper_download_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsLetterEmail', models.EmailField(max_length=60)),
                ('Submitted_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
