# Generated by Django 4.1 on 2023-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0011_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers_table',
            name='JobOrderID',
        ),
        migrations.AlterField(
            model_name='careers_table',
            name='Submitted_on',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
