# Generated by Django 4.1.5 on 2024-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0012_remove_careers_table_joborderid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(max_length=1000)),
                ('pnumber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='alt',
            field=models.CharField(blank=True, default='Ebook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='perma_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='alt',
            field=models.CharField(blank=True, default='Ebook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='perma_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
