# Generated by Django 4.1.5 on 2024-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSSApp', '0013_podcast_ebook_pdf_alt_ebook_pdf_perma_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook_pdf',
            name='keyword',
            field=models.CharField(blank=True, default='spgamerica', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='paragraph',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='keyword',
            field=models.CharField(blank=True, default='spgamerica', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='paragraph',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
