"""
Django settings for VitelProject project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!d5j%*7j0bg+rt++e*iu=-@yckv86gvl0x&x(^8x6%4r9k^5r)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["vitelglobal.com", "www.vitelglobal.com"]


# Application definition

INSTALLED_APPS = [
    # "whitenoise.runserver_nostatic",  # changed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "captcha",
    "VitelApp",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",  # changed
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "VitelApp.custom_middleware.RemoveSlashMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "VitelProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "VitelApp.context_processors.default_context"
            ],
        },
    },
]

WSGI_APPLICATION = "VitelProject.wsgi.application"

APPEND_SLASH = True

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": "localhost",
        "NAME": "vitelglobalcomdb",
        "USER": "root",
        "PASSWORD": "K8RaT@73Eq",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # changed
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # changed


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


# # Enquiry forms Mail_Id
EMAIL_HOST = "mail.vitelglobal.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "contact@vitelglobal.com"
EMAIL_HOST_PASSWORD = "cq3o2$Iw%WFZ"
EMAIL_USE_TLS = True



RECAPTCHA_REUIRED_SCORE = 0.85


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# to fix Insecure cookie setting: missing Secure flag in django

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# $mail->Host = "mail.vitelglobal.com";
# $mail->Port = 587; // or 587 or 25
# $mail->IsHTML(true);
# $mail->SMTPSecure = 'tls';
# $mail->Username = "contact";
# $mail->Password = "bD7qgM2SE4hTv5aP";
# $mail->FromName = "Vitel Global Communications"; // From Name
# $mail->From = "contact@vitelglobal.com"; // From Email

# ------ viteldevelopment code ---------

# Voip innovations API credentials
VOIP_API_LOGIN          = "vitelglobal"
VOIP_API_PASSWORD       = "V!j%40y%4008820"
VOIP_API_WSDL_URL       = "https://backoffice.voipinnovations.com/Services/APIService.asmx?wsdl"
VOIP_API_SERVICE_URL    = "https://backoffice.voipinnovations.com/Services/APIService.asmx"
VOIP_API_METHOD_BASE_URL= "https://backoffice.voipinnovations.com/Services/"
VOIP_API_EPG            = 11982

# Vitelity API credentials

VITELITY_API_LOGIN      = "vgco_api"
VITELITY_API_PASSWORD   = "V!j%40y%4008820"
VITELITY_API_URL        = "https://api.vitelity.net/api.php" 
VITELITY_FAX_API_URL    = "https://api.vitelity.net/fax.php"