# Generated by Django 4.0.5 on 2022-07-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Organization_Name', models.CharField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
