# Generated by Django 4.0.6 on 2022-07-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0003_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='KickStart',
        ),
    ]
