# Generated by Django 4.0.6 on 2022-07-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0004_delete_contactus_delete_kickstart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='Email_Id',
            new_name='NewsLetterEmail',
        ),
    ]
