# Generated by Django 4.0.6 on 2022-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0005_rename_email_id_subscribe_newsletteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='KickStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Phone_No', models.BigIntegerField()),
                ('Company', models.CharField(max_length=50)),
                ('Size_Of_Company', models.CharField(max_length=10)),
                ('How_You_Know_Us', models.CharField(max_length=100)),
            ],
        ),
    ]
