# Generated by Django 4.0.6 on 2022-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=60)),
                ('Name', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
            ],
        ),
    ]
