# Generated by Django 4.0.6 on 2022-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0008_webinars'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('CompanyName', models.CharField(max_length=50)),
                ('No_of_users', models.IntegerField()),
                ('FullName', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('WhereDidYouHear', models.CharField(max_length=50)),
            ],
        ),
    ]
