# Generated by Django 4.0.6 on 2022-07-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0011_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='partners',
            new_name='Partner_Program',
        ),
    ]
