# Generated by Django 4.0.6 on 2022-07-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0013_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback_table',
        ),
    ]
