# Generated by Django 4.0.6 on 2022-07-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0015_careers_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Careers_table',
        ),
    ]
