# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0021_careers_table_submitted_on_contactus_submitted_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedemo',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
