# Generated by Django 4.0.6 on 2022-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0023_ebook_download_whitepaper_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lastedit_date', models.DateTimeField()),
            ],
        ),
    ]
