# Generated by Django 4.0.6 on 2022-08-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0024_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
