# Generated by Django 4.0.6 on 2022-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0026_ebook_pdf_whitepaper_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoIPServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Size_Of_Company', models.CharField(max_length=10)),
                ('How_You_Know_Us', models.CharField(max_length=100)),
                ('Submitted_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
