# Generated by Django 4.0.6 on 2022-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0027_voipservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='ebook_pdf',
            name='ebook_Path',
        ),
        migrations.RemoveField(
            model_name='ebook_pdf',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='whitepaper_pdf',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='whitepaper_pdf',
            name='whitepaper_path',
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='ebook_image',
            field=models.FileField(default=None, upload_to='static/assets/E-Books/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='ebook_pdf',
            field=models.FileField(default=None, upload_to='static/assets/E-Books/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='whitepaper_image',
            field=models.FileField(default=None, upload_to='static/assets/Whitepapers/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='whitepaper_pdf',
            field=models.FileField(default=None, upload_to='static/assets/Whitepapers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebook_pdf',
            name='enumber',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='whitepaper_pdf',
            name='wnumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
