# Generated by Django 4.1.4 on 2022-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0028_podcast_remove_ebook_pdf_ebook_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Submitted_on',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
