# Generated by Django 4.1.4 on 2023-01-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0030_contactus_howyouknow'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Whom_to_send',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
