# Generated by Django 4.1.4 on 2023-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0031_contactus_whom_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook_pdf',
            name='description',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook_pdf',
            name='perma_link',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='description',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='perma_link',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
