# Generated by Django 4.0.6 on 2023-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0032_ebook_pdf_description_ebook_pdf_perma_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
