# Generated by Django 4.0.6 on 2023-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0033_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_url', models.CharField(max_length=255)),
                ('Redirect_to', models.CharField(max_length=255)),
            ],
        ),
    ]
