# Generated by Django 4.0.6 on 2024-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0034_dynamicqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('CompanyName', models.CharField(max_length=256)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Modified_On', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Demo_Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selected_date', models.DateField()),
                ('Time', models.TimeField()),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Modified_On', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
