# Generated by Django 4.0.6 on 2024-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0035_get_quote_request_demo_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook_pdf',
            name='alt',
            field=models.CharField(blank=True, default='ebook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper_pdf',
            name='alt',
            field=models.CharField(blank=True, default='ebook', max_length=100, null=True),
        ),
    ]
