# Generated by Django 4.0.6 on 2024-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0036_ebook_pdf_alt_whitepaper_pdf_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_demo_now',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request_demo_now',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
