# Generated by Django 4.0.6 on 2024-03-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0039_setup_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kickstart',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='partner_program',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
