# Generated by Django 4.0.6 on 2024-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0040_contactus_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers_table',
            name='JobOrderID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
