# Generated by Django 4.0.6 on 2024-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0041_careers_table_joborderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=56)),
                ('unsubscribe_promotional', models.BooleanField(default=False)),
                ('unsubscribe_notifications', models.BooleanField(default=False)),
                ('unsubscribe_all', models.BooleanField(default=False)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Modified_On', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
