# Generated by Django 4.0.6 on 2022-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0009_livedemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Experience', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
