# Generated by Django 4.0.6 on 2022-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0014_rename_feedback_feedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='Resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
