# Generated by Django 4.0.6 on 2022-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0016_rename_careers_careers_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
