# Generated by Django 4.0.6 on 2022-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0017_alter_careers_table_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers_table',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='Suggestion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='kickstart',
            name='Phone_No',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livedemo',
            name='No_of_users',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livedemo',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner_program',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
