# Generated by Django 4.0.6 on 2022-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0018_alter_careers_table_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_table',
            name='Resume',
            field=models.FileField(upload_to='files'),
        ),
    ]
