# Generated by Django 4.0.6 on 2022-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0019_alter_careers_table_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webinars',
            new_name='Webinars_table',
        ),
        migrations.AlterField(
            model_name='careers_table',
            name='Resume',
            field=models.FileField(upload_to=''),
        ),
    ]
