# Generated by Django 4.0.6 on 2022-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0020_rename_webinars_webinars_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers_table',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kickstart',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partner_program',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webinars_table',
            name='Submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
