# Generated by Django 4.0.6 on 2022-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0022_livedemo_submitted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('submitted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitepaper_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50)),
                ('submitted_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
