# Generated by Django 4.0.6 on 2022-08-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitelApp', '0025_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumber', models.IntegerField(null=True)),
                ('ebook_Path', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Whitepaper_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wnumber', models.IntegerField(null=True)),
                ('whitepaper_path', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
